[global]
port = 8000
keep_alive = 5
read_timeout = 5
write_timeout = 5
template_dir = "templates/"

[development]
address = "localhost"
log = "normal"

[staging]
address = "0.0.0.0"
log = "normal"

[production]
address = "0.0.0.0"
log = "critical"
