name: Rust

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install pandoc
      run: sudo apt-get install pandoc
    - name: Run docs
      run: |
        cd docs
        rustup default nightly
        cargo run --verbose
        cd ../
    - name: Commit files
      run: |
        git config --local user.name  ${{ github.actor }}
        git add .
        git commit -m "Self updating"
    - name: Push changes  # push the output folder to your repo
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
